assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: false
  test: false
  goldcopy: true
instrument: RS03AXPS-PC03A-4B-PHSENA302
stream:
  method: streamed
  name: phsen_data_record
workflow_config:
  schedule: 0 0 * * *
